[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 300

# Note: Railway only allows one volume per service
# The volume will be automatically mounted at /data
# We'll symlink necessary directories to this volume in the entrypoint script